"""Universe providers for research and benchmark workflows."""

from cq.universe.base import Universe, UniverseNotFoundError, UniverseProvider
from cq.universe.liquid import (
    ALL_A_LIQUID_ID,
    LiquidUniverseConfig,
    LiquidUniverseProvider,
    LiquidUniverseSelection,
    StoreBackedLiquidUniverseProvider,
    build_all_a_liquid_universe,
    select_all_a_liquid_universe,
)
from cq.universe.pit import (
    PIT_MEMBERSHIP_COLUMNS,
    PIT_SCHEMA_VERSION,
    PIT_VALIDATION_SCHEMA_VERSION,
    PitImportResult,
    PitValidationExport,
    PitValidationIssue,
    PitValidationResult,
    PointInTimeUniverseProvider,
    export_pit_validation_result,
    filter_prices_by_pit_universe,
    generate_pit_validation_report,
    import_pit_memberships,
    normalize_pit_memberships,
    pit_membership_diagnostics,
    validate_pit_memberships,
)
from cq.universe.presets import (
    BUILTIN_UNIVERSES,
    get_builtin_universe_presets,
    get_builtin_universe_provider,
)
from cq.universe.sources import (
    DEFAULT_AKSHARE_INDEXES,
    DEFAULT_TUSHARE_INDEXES,
    AksharePitFetchResult,
    AksharePitSourceError,
    PitIndexSpec,
    TusharePitFetchResult,
    TusharePitSourceError,
    fetch_akshare_pit_universe,
    fetch_tushare_pit_universe,
    parse_akshare_index_specs,
    parse_tushare_index_specs,
)
from cq.universe.static import StaticUniverseProvider

__all__ = [
    "BUILTIN_UNIVERSES",
    "ALL_A_LIQUID_ID",
    "DEFAULT_AKSHARE_INDEXES",
    "DEFAULT_TUSHARE_INDEXES",
    "AksharePitFetchResult",
    "AksharePitSourceError",
    "PIT_MEMBERSHIP_COLUMNS",
    "PIT_SCHEMA_VERSION",
    "PIT_VALIDATION_SCHEMA_VERSION",
    "LiquidUniverseConfig",
    "LiquidUniverseProvider",
    "LiquidUniverseSelection",
    "PitImportResult",
    "PitIndexSpec",
    "PitValidationExport",
    "PitValidationIssue",
    "PitValidationResult",
    "PointInTimeUniverseProvider",
    "StoreBackedLiquidUniverseProvider",
    "StaticUniverseProvider",
    "TusharePitFetchResult",
    "TusharePitSourceError",
    "Universe",
    "UniverseNotFoundError",
    "UniverseProvider",
    "build_all_a_liquid_universe",
    "export_pit_validation_result",
    "fetch_akshare_pit_universe",
    "fetch_tushare_pit_universe",
    "filter_prices_by_pit_universe",
    "generate_pit_validation_report",
    "get_builtin_universe_presets",
    "get_builtin_universe_provider",
    "import_pit_memberships",
    "normalize_pit_memberships",
    "parse_akshare_index_specs",
    "parse_tushare_index_specs",
    "pit_membership_diagnostics",
    "select_all_a_liquid_universe",
    "validate_pit_memberships",
]
